global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 1m
scrape_configs:
- job_name: spring_data_from_micrometer
  honor_timestamps: true
  scrape_interval: 1s
  scrape_timeout: 1s
  metrics_path: /actuator/prometheus
  scheme: http
  static_configs:
    - targets: ['192.168.8.100:8080']
      labels:
        group: 'spring-boot'